APP_NAME = "VK Code Show"
APP_USER_MODEL_ID = "frommer.vk-code-show"
ICON_FILE_NAME = "logo.ico"
MAX_HISTORY_ROWS = 200
DEFAULT_WINDOW_WIDTH = 760
DEFAULT_WINDOW_HEIGHT = 520
MIN_WINDOW_WIDTH = 620
MIN_WINDOW_HEIGHT = 420
